[package]
name = "gem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.11"
paste = "1.0"
threadpool = "1.8.1"

[profile.rel-with-debug]
inherits = "release"
debug = true
