[package]
name = "gem"
version = "0.1.0"
edition = "2021"

[dependencies]
threadpool = "1.8.1"
lazy_static = "1.5.0"
rand = "0.8.5"
tracing = { version = "0.1.41", features = ["release_max_level_off"] }
tracing-subscriber = "0.3.19"
portable-atomic = { version = "1.10.0", default-features = false, features = ["require-cas"]}
tracing-perfetto = "0.1.4"
bitboard = { path = "../bitboard" }

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "gem_bench"
harness = false
