[package]
name = "engine"
version = "0.0.0"
edition = "2024"

[dependencies]
rand = "0.9.1"
tracing = { version = "0.1.41", features = ["release_max_level_off"] }
tracing-subscriber = "0.3.19"
portable-atomic = { version = "1.10.0", default-features = false, features = ["require-cas"]}
tracing-perfetto = "0.1.4"
bitboard = { path = "../bitboard" }
magics = { path = "../magics" }
nnue = { path = "../nnue" }
rayon = "1.10.0"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "gem_bench"
harness = false

[build-dependencies]
bitboard = { path = "../bitboard" }
magics = { path = "../magics" }

[features]
# Enable nnue based evaluation
nnue = []

