[package]
name = "tools"
version = "0.1.0"
edition = "2024"

[dependencies]
bitboard = { path = "../bitboard" }
gem = { path = "../gem" }
clap = { version = "4.5.39", features = ["derive"] }
serde_json = {version = "1.0.140", features = ["std"]}
anyhow = "1.0.98"
serde = { version = "1.0", features = ["derive"] }

[[bin]]
name = "generate_training_data"
path = "src/generate_training_data.rs"
