[package]
name = "tools"
version = "0.1.0"
edition = "2024"

[dependencies]
bitboard = { path = "../bitboard" }
gem = { path = "../gem" }
clap = { version = "4.5.39", features = ["derive"] }
serde_json = {version = "1.0.140", features = ["std"]}
anyhow = "1.0.98"
serde = { version = "1.0", features = ["derive"] }
bulletformat = { git = "https://github.com/jw1912/bulletformat" }
bullet_lib = { git = "https://github.com/jw1912/bullet" }
nnue = { path = "../nnue" }

[[bin]]
name = "train"
path = "src/bin/train.rs"

[[bin]]
name = "eval"
path = "src/bin/eval.rs"
