#!/usr/bin/env python3

import random

random.seed(0x5af3de7386fe22d3)

print("// Generated by tools/zobrist_numbers.py")
print("impl ZobristNumbers {")
print("pub const fn init() -> ZobristNumbers {")
print("    ZobristNumbers {")
print("        piece_hashes: [")
for i in range(0, 64):
    print(f"            [")
    for i in range(0, 12):
        print(f"                0x{random.randint(0,0x1000_0000_0000_0000):x},")
    print(f"            ],")
print("        ],")
print(f"        black_turn: 0x{random.randint(0,0x1000_0000_0000_0000):x},")
print(f"        black_queen_castle: 0x{random.randint(0,0x1000_0000_0000_0000):x},")
print(f"        black_king_castle: 0x{random.randint(0,0x1000_0000_0000_0000):x},")
print(f"        white_queen_castle: 0x{random.randint(0,0x1000_0000_0000_0000):x},")
print(f"        white_king_castle: 0x{random.randint(0,0x1000_0000_0000_0000):x},")
print(f"        en_passant_targets: [")
print(f"            0x{random.randint(0,0x1000_0000_0000_0000):x},")
print(f"            0x{random.randint(0,0x1000_0000_0000_0000):x},")
print(f"            0x{random.randint(0,0x1000_0000_0000_0000):x},")
print(f"            0x{random.randint(0,0x1000_0000_0000_0000):x},")
print(f"            0x{random.randint(0,0x1000_0000_0000_0000):x},")
print(f"            0x{random.randint(0,0x1000_0000_0000_0000):x},")
print(f"            0x{random.randint(0,0x1000_0000_0000_0000):x},")
print(f"            0x{random.randint(0,0x1000_0000_0000_0000):x},")
print(f"        ]")
print("    }")
print("}")
print("}")
